version: '3'
services:

  exporter:
    image: trl
    restart: always
    ports:
      - '8080:80'
    deploy:
      replicas: 7
      mode: replicated
    environment:
      - SSERROR=false

  prom-config:
    image: prom-config
    restart: always
    ports:
      - '8081:80'
    volumes:
      - '/root/prometheus/prometheus:/prometheus'